version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./tiktok
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
            - elasticsearch
            - mongo-express
            - kibana
            - redis
            - nginx
        networks:
            - nesjs-network
            - elasticsearch-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: ./tiktok
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
            - elasticsearch
            - mongo-express
            - kibana
            - redis
            - nginx
        networks:
            - nesjs-network
            - elasticsearch-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        
        networks:
            - nesjs-network
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - "28081:8081"
        depends_on:
            - mongo
    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        container_name: MY_KIBANA
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        networks: 
            - elasticsearch-network
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        container_name: MY_ELASTICSEARCH
        environment:
            - node.name=elasticsearch
            - http.port=9200
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
        memlock:
            soft: -1
            hard: -1
        ports: 
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
        volumes:
            - ./esdata/:/usr/share/elasticsearch/data/
        networks:
            - elasticsearch-network
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    nginx:
        build: ./nginx
        ports:
        - '80:80'
networks:
    nesjs-network:
        driver: bridge
    elasticsearch-network:
volumes:
    data:
    esdata:
