version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./tiktok
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
        networks:
            - nesjs-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: ./tiktok
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
            - elasticsearch
        links:
            - elasticsearch
        networks:
            - nesjs-network
            - elasticsearch-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        container_name: MY_KIBANA
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        networks: 
            - elasticsearch-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        container_name: MY_ELASTICSEARCH
        ports: 
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
        volumes:
            - ./esdata/:/usr/share/elasticsearch/data/
        networks:
            - elasticsearch-network
networks:
    nesjs-network:
    elasticsearch-network: