version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./tiktok
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
        networks:
            - nesjs-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: ./tiktok
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - mongo
        networks:
            - nesjs-network
        volumes:
            - ./tiktok:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"
networks:
    nesjs-network: